[shell-installers]
install = ["rustup"]

[brew]
formulae = [
    "bat",
    "borgbackup",  # Use Borg for backups.
    "borgmatic",   # Simplifies backup.
    "cmus",
    "dust",        # Pretty `du`, written in Rust.
    "duckdb",
    "exiftool",
    "eza",         # Pretty successor to `exa` and `ls`, written in Rust.
    "fd",          # Successor to `find`, written in Rust.
    "fish",
    "gemini-cli",
    "git",
    "git-delta",
    "helix",
    "hexyl",
    "imagemagick",
    "just",        # Just the parts of `make` that I mostly use.
    "jq",
    "mas",         # Necessary to be able to install App store Apps.
    "mpd",
    "neovim",      # nvim is an alias in brew for neovim.
    "pass",
    "ripgrep",     # Successor to `ag`, `grep`, written in Rust.
    "starship",
    "sqlite",
    "uv",          # I have had it with these monkey-fighting snakes on this Monday-to-Friday plane!
    "wget",
    "zola",
]
casks = [
    "anki",
    "balenaetcher",
    "font-fira-code-nerd-font",    # I'm happiest coding in Fira Code.
    "font-iosevka-term-nerd-font", # A slimmer font, gives me more columns.
    "ghostty",                     # The last terminal emulator that I ever install?
    "google-chrome",
    "handbrake",
    "keepassxc",
    "makemkv",
    "musicbrainz-picard",
    "obsidian",
    "openscad",
    "orcaslicer",
    "pocket-casts",
    "raspberry-pi-imager",
    "rectangle",
    "signal",
    "slack",
    "utm",
    "visual-studio-code",
    "vlc",
    "xld",
    "zoom",
]

[mas]
apps = [{ name = "Amphetamine", id = "937984704" }]

[dotfiles]
files = [
    ".config/bat/config",

    # cmus themes.
    ".config/cmus/themes/green-mono-88.theme",
    ".config/cmus/themes/solarized-dark.theme",

    ".config/eza/theme.yml",

    # fish shell files.
    ".config/fish/config.fish",
    ".config/fish/conf.d/abbreviations.fish",

    ".config/ghostty/config",
    ".config/ghostty/shaders/amber-crt.glsl",
    ".config/ghostty/shaders/blue-crt.glsl",
    ".config/ghostty/shaders/green-crt.glsl",

    ".config/git/config",

    # mpd on macOS installed through homebrew is not XDG-compliant.
    ".mpd/mpd.conf",

    ".config/readline/inputrc",

    ".config/starship.toml",
    # VSCode user `settings.json` is not XDG-compliant on macOS, and there's no
    # way to overwrite it with environment variables.
    "Library/Application Support/Code/User/settings.json",
]

[vscode]
extensions = [
    "eamodio.gitlens",
    # Extension for developing GitHub Actions.
    "GitHub.vscode-github-actions",
    # Good vibes, good code!
    "google.gemini-cli-vscode-ide-companion",
    # Generic container tooling that also has Podman support.
    "ms-azuretools.vscode-containers",
    # SSH into remote machines and edit code there.
    "ms-vscode-remote.remote-ssh",
    # Rust Analyzer, because I deserve nice things.
    "rust-lang.rust-analyzer",
    # My go-to spell checker for VSCode.
    "streetsidesoftware.code-spell-checker",
    # TOML formatting.
    "tamasfe.even-better-toml",
    "usernamehw.errorlens",
    # Absolutely necessary to be able to type.
    "vscodevim.vim",
]

[macos.system]
# We're all consenting adults here.
show-file-extensions = true
# Referred to as "natural" scrolling by Apple; I have never encountered anything
# more un-natural.
weird-mac-scrolling = false
# Apple Press&Hold allows you to select alternative characters on long presses.
# I've never used this feature, and it causes issues with vim navigation.
key-press-and-hold = false
# Waiting for key repeat to start? Ain't nobody got time for that.
initial-key-repeat-wait = 14
# Makes hold-down key repeats feel _FAST_!
key-repeat-rate = 1
# I can capitalize my own words, thank you very much.
automatic-capitalization = false

[macos.dock]
# Left-side is the best side.
orientation = "left"
# Get a bit of screen real estate back.
autohide = true
icon-size = 65
# Hidden apps have transparent icons in the dock.
transparent-hidden-app-icons = true

[macos.mission-control]
# Automatically rearrange spaces based on most recently used. How annoying!
# Don't move my cheese!
automatically-rearrange-spaces = false
# Group apps together when viewing all apps in mission control.
group-apps = true

[macos.safari]
# I can handle the full URL, thanks.
show-full-url = true

[macos.magic-mouse]
# The options are "one-button", and "two-button".k
mouse-button-mode = "two-button"

[macos.finder]
# Display directory breadcrumbs at the bottom of the finder window. This is
# helpful for me to orient my location in the filesystem and allow me to easily
# jump up a few directories.
show-pathbar = true
# Also helpful to figure out where you are in the filesystem.
show-full-posix-path-in-title-bar = true
